Repository GreenfootSeatingChartMaster2022-23-P7/GreenfootSeatingChartMaster2022-23-P7, pull requests merged in 2022-09, with the labels that each got.

#35 WaleedRydhan files
  .DS_Store
  Classroom.java
  WaleedRydhan.java
  images/sathvikanadipalli.jpg
  images/waleedrydhan(big-pic).jpg
  images/waleedrydhan(fried).jpg
  images/waleedrydhan-standing.jpg
  images/waleedrydhan.jpg
  sounds/waleedrydhan.mp3
Labels: submit new pull request

#18 added code and images
  AbhinithiJanardhanan.java
  Classroom.java
  images/.DS_Store
  images/abhinithijanardhanan-standing.jpg
  images/abhinithijanardhanan.jpg
  project.greenfoot
  sounds/.DS_Store
  sounds/abhinithijanardhanan.wav
Labels: bug, missing classroom.java

#24 Add files via upload
  AnishaRao.java
  Classroom.java
  images/anisharao-standing.jpg
  images/anisharao.jpg
  sounds/anisharao.wav
Labels: bug, missing classroom.java

#81 add neelsharma files
  Classroom.java
  NeelSharma.java
  images/neelsharma-standing.jpg
  images/neelsharma.jpg
  sounds/neelsharma.wav
Labels: bug

#82 Ankita k
  AnkitaKumar.java
  Classroom.java
  images/ankitakumar.jpg
  sounds/ankitakumar.wav
Labels: bug

#69 Add Sahil Sandasani's files
  Classroom.java
  SahilSandasani.java
  images/sahilsandasani-standing.jpg
  images/sahilsandasani.jpg
  sounds/sahilsandasani.wav
Labels: bug, submit new pull request
